#!/bin/sh

set -e

lb config noauto \
        --architecture "i386" \
        --linux-flavours "686-pae" \
        --distribution "wheezy" \
        --binary-images "netboot" \
        --memtest "none" \
        --apt-recommends "false" \
        --apt-indices "false" \
        --archive-areas "main contrib non-free" \
        --bootappend-live "console=ttyS0 loglevel=3 boot=live config hostname=sebian username=sebianuser locale=de_DE.UTF-8 keyboard-layouts=de netboot=nfs nfsroot=192.168.2.10:/srv/debian-live" \
        "${@}"

