#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

# just a hack for my virtual network

StoreProfile ()
{
	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
	cd /home
	ls -la "${LIVE_USERNAME}/"
	tar czf "${LIVE_USERNAME}.tgz" "${LIVE_USERNAME}"
	chmod 740 "${LIVE_USERNAME}.tgz"
}

StoreProfile
